spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: recommendations

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: admin
    password: admin

server:
  port: 9094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

