spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-user-db
    username: postgres
    password: Lt*08161554409

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka